package com.example.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.services.rekognition.model.Image;

import java.util.List;

@Data
@DynamoDBTable(tableName = "customer")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Customer {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String id;

    @DynamoDBAttribute
    public String name;

    @DynamoDBAttribute
    public String email;

    @DynamoDBAttribute
    public String url_face;
}
