package com.example.model;

import java.time.Instant;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

@Data
@DynamoDBTable(tableName = "Order")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Order {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String customerID;

    @DynamoDBAttribute
    private String orderSerial;

    @DynamoDBAttribute
    private double orderValue;

    @DynamoDBAttribute
    private Instant createdDate;

    @Id
    @DynamoDBAttribute
    private OrderID orderID;

    @DynamoDBAttribute
    private List<Product> products;

    public Order(OrderID orderID) {
        super();
        this.orderID = orderID;
    }
}